server:
  port: @server.port@
management:
  security:
    flag: false
  metrics:
    export:
      statsd:
        flavor: etsy
  endpoint:
    health:
      show-details: always

spring:
  application:
    name: @project.name@
  output:
    ansi:
      enabled: always
info:
  version: @project.version@
  stage: dev
service: test-adapter
hostname: '#{T(java.net.InetAddress).getLocalHost().getHostName()}'
consul:
  enabled: false
  hosts: #consul hosts
  blacklistTimeInMillis: 500
  keyPath: mockapter/${service}/hosts/${hostname}

configuration.resource: classpath:default-configuration.json
