server:
  port: @server.port@
management:
  security:
    flag: false
  metrics:
    export:
      statsd:
        flavor: etsy
spring:
  application:
    name: @project.name@
  output:
    ansi:
      enabled: always
info:
  version: @project.version@
  stage: dev
service: test-adapter
hostname: '#{T(java.net.InetAddress).getLocalHost().getHostName()}'
consul:
  hosts: consul1.bst1.rbkmoney.net:8500,consul2.bst1.rbkmoney.net:8500,consul3.bst1.rbkmoney.net:8500
  blacklistTimeInMillis: 500
  keyPath: mockapter/${service}/hosts/${hostname}
  configuration: classpath:default-configuration.json
